### ISSUE TITLE
electron app seems break

### ISSUE THREAD

**Issue by josselinchevalay** [moxystudio/node-proper-lockfile#84]
hello, 

is use a npm module wich use your project and when i try to run my application into electron i have this issue : 

```
/node_modules/proper-lockfile/lib/lockfile.js:47
                    return acquireLock(file, { ...options, stale: 0 }, callback);
                                               ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.require.extensions.(anonymous function) [as .js] (/home/josselin/develop/telescope/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/josselin/develop/telescope/node_modules/proper-lockfile/index.js:3:18)
    at Object.<anonymous> (/home/josselin/develop/telescope/node_modules/proper-lockfile/index.js:42:3)```

any idea ? 

Regards

**Comment by satazor** [comment]
It seems that the nodejs version you are using is really old because it doesn’t support object spread.

**Comment by elantion** [comment]
Try to find out node.js version by using ```process.versions```, if under v8.3, it doesn't have object spread feature by default. @josselinchevalay

**Comment by satazor** [comment]
Closing this as this issue is not related to this package.
