### ISSUE TITLE
Cannot read property 'updateTimeout' of undefined

### ISSUE THREAD

**Issue by linonetwo** [moxystudio/node-proper-lockfile#98]
I got following error, when I close an electron app window, and click the tray icon to restart that app.

```
Uncaught Exception:
TypeError: Cannot read property 'updateTimeout' of undefined
    at updateLock (/xxx/SoLiDBox.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/lockfile.js:90:14)
    at /xxx/SoLiDBox.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/lockfile.js:136:13
    at FSReqCallback.oncomplete (fs.js:153:23)
```

**Comment by linonetwo** [comment]
Oh, it is in version v3.
